### ISSUE TITLE
Broken CruchyData containers repo link

### ISSUE THREAD

**Issue by cschroedl-gov** [thesteve0/workshops#1]
A link to the crunchy data containers in the FOSS4GNA 2016 ascii doc 404's when visited.

**Comment by cschroedl-gov** [comment]
Should this be included?
https://github.com/CrunchyData/crunchy-postgres-container-client

**Comment by thesteve0** [comment]
Broken by design. It will start working tomorrow after Jeff opens up the
repo. It is private for now and you folks are the first group to actually
play with the bits
